CREATE TABLE `CATEGORIAS_MOVIMIENTOS` (
  `ID_CATEGORIA` int NOT NULL,
  `DESCRIPCION` varchar(50) DEFAULT NULL,
  `ID_TIPO_MOVIMIENTO` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE `CIUDAD` (
  `ID_CIUDAD` int NOT NULL,
  `NOMBRE_CIUDAD` varchar(100) NOT NULL,
  `ID_COMUNA` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `COMUNA` (
  `ID_COMUNA` int NOT NULL,
  `NOMBRE_COMUNA` varchar(100) NOT NULL,
  `ID_REGION` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE `DETALLE_MOVIMIENTO` (
  `ID_DETALLE_MOVIMIENTO` int NOT NULL,
  `ID_MOVIMIENTO` int DEFAULT NULL,
  `ID_LOTE` int DEFAULT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO` int NOT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ITEM` int DEFAULT NULL,
  `ID_PRODUCTO` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE `DIRECCIONES` (
  `ID_DIRECCION` int NOT NULL,
  `CALLE` varchar(255) NOT NULL,
  `NUMERO` int NOT NULL,
  `ID_CIUDAD` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE `EMPRESAS` (
  `ID_EMPRESA` int NOT NULL,
  `NOMBRE_EMPRESA` varchar(100) NOT NULL,
  `TELEFONO_EMPRESA` int DEFAULT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ESTADO` int DEFAULT NULL,
  `USUARIO_ACTUALIZA` int DEFAULT NULL,
  `RUT_EMPRESA` varchar(20) NOT NULL,
  `ID_DIRECCION` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `ESTADO` (
  `ID_ESTADO` int NOT NULL,
  `DESCRIPCION_ESTADO` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `HISTORIAL_PRECIOS` (
  `ID_HISTORIAL_PRECIO` int NOT NULL,
  `ID_PRODUCTO` int DEFAULT NULL,
  `PRECIO` int NOT NULL,
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `LOGS_USUARIOS` (
  `ID_LOG` int NOT NULL,
  `ID_USUARIO` int DEFAULT NULL,
  `ACCION` varchar(255) NOT NULL,
  `FECHA_ACCION` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `LOTES_PRODUCTOS` (
  `ID` int NOT NULL,
  `ID_LOTE` int NOT NULL,
  `ID_PRODUCTO` int DEFAULT NULL,
  `FECHA_VENCIMIENTO` date NOT NULL,
  `CANTIDAD` int NOT NULL,
  `PRECIO_COMPRA` int NOT NULL,
  `PRECIO_VENTA` int NOT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `LOTES_VENCIDOS` (
  `ID_LOTE_VENCIDO` int NOT NULL,
  `ID_LOTE` int DEFAULT NULL,
  `ID_PRODUCTO` int DEFAULT NULL,
  `CANTIDAD_VENCIDA` int NOT NULL,
  `FECHA_VENCIMIENTO` date NOT NULL,
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `MOVIMIENTOS` (
  `ID_MOVIMIENTO` int NOT NULL,
  `TIPO_MOVIMIENTO` int DEFAULT NULL,
  `ID_USUARIO` int DEFAULT NULL,
  `FECHA_MOVIMIENTO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NOTA` varchar(255) DEFAULT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_CATEGORIA` int DEFAULT NULL,
  `ID_TIPO_PAGO` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `PAIS` (
  `ID_PAIS` int NOT NULL,
  `NOMBRE_PAIS` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `PRODUCTOS` (
  `ID_PRODUCTO` int NOT NULL,
  `NOMBRE_PRODUCTO` varchar(100) NOT NULL,
  `DESCRIPCION_PRODUCTO` text,
  `UNIDAD_MEDIDA` int DEFAULT NULL,
  `ID_PROVEEDOR` int DEFAULT NULL,
  `ID_EMPRESA` int DEFAULT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `PRODUCTOS_MERMA` (
  `ID_MERMA` int NOT NULL,
  `ID_PRODUCTO` int DEFAULT NULL,
  `ID_LOTE` int DEFAULT NULL,
  `CANTIDAD` int NOT NULL,
  `RAZON_MERMA` int DEFAULT NULL,
  `DESCRIPCION` varchar(255) DEFAULT NULL,
  `COSTO_MERMA` int NOT NULL,
  `FECHA_REGISTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `PROVEEDORES` (
  `ID_PROVEEDOR` int NOT NULL,
  `NOMBRE_PROVEEDOR` varchar(100) NOT NULL,
  `NOMBRE_CONTACTO` varchar(100) DEFAULT NULL,
  `TELEFONO_CONTACTO` varchar(20) DEFAULT NULL,
  `EMAIL_CONTACTO` varchar(100) DEFAULT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_DIRECCION` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `RAZON_MERMA` (
  `ID_RAZON_MERMA` int NOT NULL,
  `DESCRIPCION_RAZON` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `REGION` (
  `ID_REGION` int NOT NULL,
  `NOMBRE_REGION` varchar(100) NOT NULL,
  `ID_PAIS` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `ROL` (
  `ID_ROL` int NOT NULL,
  `DESCRIPCION_ROL` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TIPO_MOVIMIENTO` (
  `ID_TIPO_MOVIMIENTO` int NOT NULL,
  `DESCRIPCION_MOVIMIENTO` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `TIPO_PAGO` (
  `ID_TIPO_PAGO` int NOT NULL,
  `DESCRIPCION_PAGO` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `UNIDAD_MEDIDA` (
  `ID_UNIDAD_MEDIDA` int NOT NULL,
  `DESCRIPCION_UNIDAD` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `USUARIOS` (
  `ID_USUARIO` int NOT NULL,
  `NOMBRE_USUARIO` varchar(50) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `CONTRASENIA` varchar(255) NOT NULL,
  `NOMBRE` varchar(50) DEFAULT NULL,
  `APATERNO` varchar(50) DEFAULT NULL,
  `AMATERNO` varchar(50) DEFAULT NULL,
  `TELEFONO` varchar(20) DEFAULT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ESTADO` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `USUARIO_EMPRESA` (
  `ID_USUARIO_EMPRESA` int NOT NULL,
  `ID_USUARIO` int DEFAULT NULL,
  `ID_EMPRESA` int DEFAULT NULL,
  `ROL` int DEFAULT NULL,
  `CREADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTUALIZADO_EN` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
