CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_01_LOGIN` (IN `p_USUARIO` VARCHAR(100), IN `p_CONTRASENIA` VARCHAR(20))   
BEGIN
    SELECT  T1.ID_USUARIO,
            T1.EMAIL,
            T1.NOMBRE_USUARIO,
            T2.ROL,
            T1.NOMBRE,
            T1.APATERNO
    FROM USUARIOS T1
    JOIN USUARIO_EMPRESA T2 ON T1.ID_USUARIO = T2.ID_USUARIO
    WHERE UPPER(T1.EMAIL) = UPPER(p_USUARIO) 
      AND T1.CONTRASENIA = p_CONTRASENIA 
      AND T1.ESTADO = 1;
END$$
