CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_10_LLENADO_MOVIMIENTOS` (IN `P_IDUSUARIO` INT)  
NO SQL 
BEGIN
	SELECT T1.ID_MOVIMIENTO,
           T2.DESCRIPCION_MOVIMIENTO,
           T3.NOMBRE AS RESPONSABLE,
           T1.FECHA_MOVIMIENTO,
           T1.NOTA,
           (SUM(T4.PRECIO * T4.CANTIDAD)) AS TOTAL_MOVIMIENTO,
           T5.DESCRIPCION,
           T6.DESCRIPCION_PAGO
    FROM MOVIMIENTOS T1
    JOIN TIPO_MOVIMIENTO T2 ON T1.TIPO_MOVIMIENTO = T2.ID_TIPO_MOVIMIENTO
    JOIN USUARIOS T3 ON T3.ID_USUARIO = T1.ID_USUARIO
    JOIN DETALLE_MOVIMIENTO T4 ON T4.ID_MOVIMIENTO = T1.ID_MOVIMIENTO
    JOIN CATEGORIAS_MOVIMIENTOS T5 ON T5.ID_CATEGORIA = T1.ID_CATEGORIA
    JOIN TIPO_PAGO T6 ON T6.ID_TIPO_PAGO = T1.ID_TIPO_PAGO
    JOIN USUARIO_EMPRESA T7 ON T7.ID_USUARIO = T3.ID_USUARIO
    JOIN EMPRESAS T8 ON T8.ID_EMPRESA = T7.ID_EMPRESA
    WHERE T7.ID_EMPRESA = (SELECT ID_EMPRESA FROM USUARIO_EMPRESA WHERE ID_USUARIO = P_IDUSUARIO)
    GROUP BY T1.ID_MOVIMIENTO,
             T2.DESCRIPCION_MOVIMIENTO,
             T3.NOMBRE,
             T1.FECHA_MOVIMIENTO,
             T1.NOTA,
             T5.DESCRIPCION,
             T6.DESCRIPCION_PAGO;
END$$
