CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_11_LLENADO_DETALLE_MOVIMIENTO` (IN `P_IDMOVIMIENTO` INT)  
NO SQL 
BEGIN
	SELECT 
    T1.ID_MOVIMIENTO,
    T1.ITEM, 
    T1.ID_LOTE, 
    T1.CANTIDAD, 
    T1.PRECIO,
    T2.DESCRIPCION_PRODUCTO,
    SUM(T1.CANTIDAD * T1.PRECIO) AS TOTAL
    FROM DETALLE_MOVIMIENTO T1
    JOIN PRODUCTOS T2 ON T1.ID_PRODUCTO = T2.ID_PRODUCTO
    WHERE T1.ID_MOVIMIENTO = P_IDMOVIMIENTO
    GROUP BY 
    T1.ID_MOVIMIENTO,
    T1.ITEM, 
    T1.ID_LOTE, 
    T1.CANTIDAD, 
    T1.PRECIO,
    T2.DESCRIPCION_PRODUCTO;
END$$
