CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_02_LLENADO_PERFIL` (IN `p_IDUSER` INT)   
BEGIN
    SELECT 
        T1.NOMBRE_USUARIO,
        T1.EMAIL,
        T1.NOMBRE,
        T1.APATERNO,
        T1.AMATERNO,
        T1.TELEFONO
    FROM USUARIOS T1
    JOIN ESTADO T2 ON T1.ESTADO = T2.ID_ESTADO
    WHERE T1.ID_USUARIO = p_IDUSER;
END$$
