CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_03_TABLA_GESTION_USUARIOS` (IN `P_IDUSUARIO` INT)   
BEGIN
    SELECT
        T1.ID_USUARIO,
        T1.NOMBRE_USUARIO,
        T1.EMAIL,
        T1.ESTADO
    FROM USUARIOS T1
    JOIN USUARIO_EMPRESA T2 ON T1.ID_USUARIO = T2.ID_USUARIO
    WHERE T2.ROL = 2 
      AND T2.ID_EMPRESA = (SELECT ID_EMPRESA FROM USUARIO_EMPRESA WHERE ID_USUARIO = P_IDUSUARIO LIMIT 1);
END$$
