CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_05_ACTUALIZAR_USUARIO_DATOS` (
IN `p_ID_USUARIO` INT, 
IN `p_NOMBRE_USUARIO` VARCHAR(100), 
IN `p_EMAIL` VARCHAR(100), 
IN `p_NOMBRE` VARCHAR(100), 
IN `p_APATERNO` VARCHAR(100), 
IN `p_AMATERNO` VARCHAR(100), 
IN `p_TELEFONO` VARCHAR(20))   
BEGIN
    UPDATE USUARIOS
    SET 
        NOMBRE_USUARIO = p_NOMBRE_USUARIO,
        EMAIL = p_EMAIL,
        NOMBRE = p_NOMBRE,
        APATERNO = p_APATERNO,
        AMATERNO = p_AMATERNO,
        TELEFONO = p_TELEFONO
    WHERE ID_USUARIO = p_ID_USUARIO;
    
    IF ROW_COUNT() = 0 THEN
        SELECT 0 AS VALIDACION;
    ELSE
        SELECT 1 AS VALIDACION;
    END IF;
END$$
