CREATE DEFINER=`c2611566_soqus`@`%` PROCEDURE `PR_07_NUEVO_USUARIO` (
    IN `p_NOMBRE_USUARIO` VARCHAR(50),
    IN `p_EMAIL` VARCHAR(100),
    IN `p_CONTRASENIA` VARCHAR(255),
    IN `p_NOMBRE` VARCHAR(50),
    IN `p_APATERNO` VARCHAR(50),
    IN `p_AMATERNO` VARCHAR(50),
    IN `p_TELEFONO` VARCHAR(15),
    IN `p_IDESTADO` INT,
    IN `p_IDEMPRESA` INT,
    IN `P_IDROL` INT
)  
NO SQL 
BEGIN
    -- Insertar en la tabla USUARIOS
    INSERT INTO USUARIOS (
        NOMBRE_USUARIO,
        EMAIL, 
        CONTRASENIA,
        NOMBRE,
        APATERNO,
        AMATERNO,
        TELEFONO,
        ESTADO
    )
    VALUES (
        p_NOMBRE_USUARIO,
        p_EMAIL,
        p_CONTRASENIA,
        p_NOMBRE,
        p_APATERNO,
        p_AMATERNO,
        p_TELEFONO,
        p_IDESTADO
    );

    -- Insertar en la tabla USUARIO_EMPRESA
    INSERT INTO USUARIO_EMPRESA (ID_USUARIO, ID_EMPRESA, ROL)
    VALUES (
        (SELECT ID_USUARIO FROM USUARIOS WHERE NOMBRE_USUARIO = p_NOMBRE_USUARIO),
        p_IDEMPRESA,
        p_IDROL
    );
END$$
